window.HotBDrillLibrary = [
  {
    "name": "Basic Tee Work",
    "category": "Warm-Up",
    "primaryPurpose": "Prepare the body and reinforce adjustable posture and barrel path throughout the strike zone",
    "secondaryFocus": "Zone awareness and swing adjustability",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Work inside, outside, high and low tee positions",
    "coachingCues": "Move the tee around the zone and focus on how you should change your body and mechanics to accommodate different pitches.",
    "success": "Hard line-drive contact from gap to gap from all tee locations",
    "bestUsedFor": "Pre-practice warm-up; recalibrating posture and barrel path; preparing to cover the full zone",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Skater Drill",
    "category": "Power",
    "primaryPurpose": "Maintain centered balance while moving pressure between the front and back sides",
    "secondaryFocus": "Prevent your weight from being too far forward or being up on your front foot",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up 6-10 inches back towards catcher with your feet together. Hop towards pitcher and land on front foot only, then hop towards catcher and land on back foot only, then hop forward again, hop to back foot, then stride into your full swing.",
    "coachingCues": "Keep your weight centered and balanced as you hop and into your stride / hit.",
    "success": "More powerful contact than a regular hit, should be center field line drives.",
    "bestUsedFor": "Drifting forward; getting onto the front foot early; weak contact caused by poor balance",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Step In - Strong Stride",
    "category": "Power",
    "primaryPurpose": "Create a forceful, controlled forward move into the swing",
    "secondaryFocus": "Lower-half aggression and balance",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set stance, take one large step back away from the plate. Set up, step in to normal spot with your back foot, take large aggressive stride forward with your front foot, and hit.",
    "coachingCues": "Keep your weight centered and balanced as you stride / hit.",
    "success": "More powerful contact than a regular hit, should be center field line drives.",
    "bestUsedFor": "Passive stride; weak contact; hitter needs a stronger forward move",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Step Up/In - Strong Stride",
    "category": "Power",
    "primaryPurpose": "Build momentum into a strong stride without losing posture or balance",
    "secondaryFocus": "Lower-half sequencing and aggression",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set stance, take one large step back away from the plate and one large step back towards the catcher. Set up, step up and in with your back foot into it's normal spot, then take large aggressive stride forward with your front foot, and hit.",
    "coachingCues": "Keep your weight centered and balanced as you stride / hit.",
    "success": "More powerful contact than a regular hit, should be center field line drives.",
    "bestUsedFor": "Weak forward move; limited lower-half momentum; weak contact",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Ball on Shoulder",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Keep the hands and barrel from dropping during the load",
    "secondaryFocus": "Calm hands",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set stance, place a softball on your back shoulder (where you bat would normally rest), set your bat on top of the ball, so the bat and your shoulder are holding the ball in place. Go into your swing, only eliminate your separation and go from load to the beginning of your swing without the ball falling off your shoulder. Then release the bat / swing and hit ball. The ball should fall foward towards the plate.",
    "coachingCues": "Keep your hands / bat calm. Stay set and centered during your load. Keeps your hands from dropping when you go into your load.",
    "success": "Line drives. No pop flies.",
    "bestUsedFor": "Pop-ups; frequent foul balls; hands dropping during the load; contact under the ball",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "2Tee - Front/Back",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Keep the barrel above the rear ball and enter the hitting zone on a level path",
    "secondaryFocus": "Level Barrel Head",
    "hittingMethod": "Tee",
    "equipment": "Two Tees, Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up a single tee in normal spot. Set second tee about 12-inches behind the first tee and set the ball about 6-inches lower than the first tee. Swing and hit the front tee without touching the back ball on the back tee.",
    "coachingCues": "Keep your hands from dropping by not hitting the back ball.",
    "success": "Line drives. No pop flies.",
    "bestUsedFor": "Pop-ups; dropped hands; steep down-up swing; contact under the ball",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "2Tee - Inside/Outside",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Recognize pitch location late and adjust the swing path without pausing",
    "secondaryFocus": "Inside / Outside Pitches",
    "hittingMethod": "Tee",
    "equipment": "Two Tees, Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up a tee as a low inside pitch (make sure it's moved up in zone) and the second tee as a high outside pitch (move tee back so it's centered on your stance). As one girl loads and starts to engage her swing, her partner says \"inside\" or \"outside, and the girl at the plate has to hit what she calls.  As it progesses, wait later in the swing to to call the pitch.",
    "coachingCues": "Keep your hands in tight to start, the start of the swing should be the same and alter only after you know what your going after.",
    "success": "One smooth motion when hitting either pitch and consistent contact. Don't pause or studder.",
    "bestUsedFor": "Slow pitch-location decisions; difficulty covering inside and outside pitches; one-swing-only pattern",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Speed Side Toss",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Make rapid swing-path adjustments to changing pitch locations",
    "secondaryFocus": "Eye Hand coordination",
    "hittingMethod": "Side Toss",
    "equipment": "Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up to hit, second person sets up to side toss. Toss as quickly as you can for as long as the person can last.  Hit every pitch they throw while changing your swing and body mechanics to compensate for the the pitch location.",
    "coachingCues": "Swing all the way through, be quick back to reset. Change your swing and body to get to the ball for good contact.",
    "success": "Good eye-hand coordiation with good consistent contact for every ball in all the zones.",
    "bestUsedFor": "Slow visual decisions; poor eye-hand coordination; difficulty adjusting to unexpected pitch locations",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Regular Side Toss",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Adjust posture and barrel path to pitches throughout the strike zone",
    "secondaryFocus": "Eye Hand coordination",
    "hittingMethod": "Side Toss",
    "equipment": "Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Tosser gives a variety of pitches, In, Out, High, Low. Variety, add an 0-2 count, so they have to swing for contact. Change swing and body mechanics to compensate for the the pitch location.",
    "coachingCues": "There are a variety of cues depending on what they are doing. Look for consistent hard contact from gap to gap.",
    "success": "Good eye-hand coordiation with good consistent contact for every ball in all the zones.",
    "bestUsedFor": "Poor zone coverage; one-swing-only pattern; two-strike contact; inconsistent contact by pitch location",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Pitch Behind",
    "category": "Timing",
    "primaryPurpose": "Delay commitment while staying ready to accelerate through contact",
    "secondaryFocus": "Contact point and late adjustability",
    "hittingMethod": "Rear Toss",
    "equipment": "Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up to hit, second person sets up behind person by 8 feet and tosses the ball thru the strike zone (aim a little outside to start with). Hitter has to wait on ball to travel thru zone to front part of plate and explode to contact.",
    "coachingCues": "Wait for the ball to travel to the front part of the plate. Swing fast and drive it straight ahead.",
    "success": "The more CF the ball travels the better. This shows too early, too late really well.",
    "bestUsedFor": "Early commitment; lunging; difficulty letting the ball travel; weak contact on offspeed pitches",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Plate Recognition",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Identify ball/strike status and pitch location early enough to make a quality swing decision",
    "secondaryFocus": "Picking a pitch you can Drive",
    "hittingMethod": "Front Toss",
    "equipment": "Tee, Plate",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up six balls across the plate from inside (1) to outside (6). Throw front toss and the hitter has to call out the number the pitch after she either lets it go, or swings.",
    "coachingCues": "Recognize location early; take pitches outside the target zone; attack pitches that can be driven",
    "success": "Correct ball/strike and location calls followed by hard contact on selected pitches",
    "bestUsedFor": "Chasing outside the zone; taking hittable pitches; poor pitch-location recognition; weak swing decisions",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Front Toss",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Transfer mechanical adjustments into timing and hard contact against a moving ball",
    "secondaryFocus": "Pitch recognition and gap-to-gap contact",
    "hittingMethod": "Front Toss",
    "equipment": "L-screen, balls, plate",
    "spaceSetup": "Tunnel",
    "howItWorks": "Set up a screen and pitch to hitter.",
    "coachingCues": "There are a variety of cues depending on what they are doing. Look for consistent hard contact from gap to gap.",
    "success": "Good eye-hand coordiation with good consistent contact for every ball in all the zones.",
    "bestUsedFor": "Testing whether tee-work adjustments transfer to a moving ball; general timing; contact quality",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Front Toss / 1 Tee Change",
    "category": "Timing",
    "primaryPurpose": "Stay loaded and adjust timing when the pitch may be a changeup",
    "secondaryFocus": "Keeping your load ready for a fast or changeup.",
    "hittingMethod": "Front Toss",
    "equipment": "Hitting Tunnel and Tee",
    "spaceSetup": "Tunnel",
    "howItWorks": "Set up a tee as an outside pitch. Throw front toss, only randomly alterante when you actually throw the pitch. When you don't throw, the hitter has to continue her swing and hit the outside tee (signifying her waiting on a changeup.",
    "coachingCues": "Be smooth, the pause should look easy. Keep your weight back, especially when you have to wait to hit the changeup.",
    "success": "Hitting pitched balls and the ball off the tee like you knew it was coming.",
    "bestUsedFor": "Early commitment on changeups; drifting forward; inability to maintain the load on offspeed pitches",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Cross Over - Strong Stride",
    "category": "Power",
    "primaryPurpose": "Feel weight transfer into a long, forceful stride while keeping the hands back",
    "secondaryFocus": "Lower-half power and sequencing",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up 6-8 inches back towards the catcher with your feet together. Take your front foot and place it on the other side of your back foot (it look like you have to pee). Lean forward with your hip only as far as you can, then go into a long stride and hit.",
    "coachingCues": "Keep you hands back, lean with your hip, and take a ong stride.",
    "success": "Really hard hit balls.",
    "bestUsedFor": "Weak contact; limited lower-half contribution; hitter does not feel weight transfer",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Machine Pitch",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Adjust to game-speed velocity, pitch location, and changing counts",
    "secondaryFocus": "Pitch-type recognition and consistent contact",
    "hittingMethod": "Machine",
    "equipment": "Pitching machine, balls, tunnel",
    "spaceSetup": "Tunnel with pitching machine",
    "howItWorks": "Use the machine at game-like speeds and locations. Mix locations, pitch types, and counts while the hitter works on recognition and hard contact.",
    "coachingCues": "Track the ball early; be on time; adjust posture to location; maintain the planned approach for the count",
    "success": "On-time hard contact on game-speed pitches in the intended part of the field",
    "bestUsedFor": "Late against velocity; difficulty adjusting to location; inconsistent contact at game speed",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Small Ball Machine",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Improve precise barrel-to-ball contact using a smaller ball and bat",
    "secondaryFocus": "Eye Hand coordination",
    "hittingMethod": "Machine",
    "equipment": "Small Ball Machine",
    "spaceSetup": "Open Space",
    "howItWorks": "Same as machine pitch only use a thin bat and it pitches really small wiffle balls.",
    "coachingCues": "Keep your eye on the ball, don't pull off, stay in the zone and focus on contact",
    "success": "Frequent centered contact with the small ball",
    "bestUsedFor": "Swing-and-miss problems; poor barrel accuracy; difficulty tracking a smaller target",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "One Leg Bucket Sits",
    "category": "Power",
    "primaryPurpose": "Generate force from the back leg before striding into the swing",
    "secondaryFocus": "Power and control",
    "hittingMethod": "Tee",
    "equipment": "Tee and Bucket",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up about 4-5 inches towards catcher. Put a bucket under your back leg, so you can sit down. Lift your front leg a couple inches off the ground. Lift yourself up using your back leg only, then stride and hit.",
    "coachingCues": "Feel the push off your back foot. Drive hard, hit hard",
    "success": "Really hard hit balls.",
    "bestUsedFor": "Weak back-side drive; poor lower-half contribution; weak contact",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Tire",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Keep the barrel level through the hitting zone without dropping the hands",
    "secondaryFocus": "Eliminating the down/up swing.",
    "hittingMethod": "Other",
    "equipment": "Tire, Bucket, Nets",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Use a short bucket and set a tire upright ontop. Set a ball ontop of the tire and hit it off without hitting the tire.",
    "coachingCues": "Stay level through the zone. Keep your hands up.",
    "success": "Clean hits without hitting the tire.",
    "bestUsedFor": "Down-up swing; dropping hands; pop-ups; contact under the ball",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Angle Hitting",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Enter the hitting zone early and keep the barrel on plane through contact",
    "secondaryFocus": "Late contact / foul balls; Early contact / pulling foul",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up like normal. Then turn your feet so your feet (toe to toe) line up to 3rd base line. Then switch to line up with 1st base line.",
    "coachingCues": "Get on line quickly, stay level through the zone.",
    "success": "Try and hit the ball gap to gap.",
    "bestUsedFor": "Short time on plane; difficulty covering offspeed pitches; weak gap-to-gap contact",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Surf Board",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Keep the barrel level through the hitting zone without a down-up path",
    "secondaryFocus": "Eliminating the down/up swing.",
    "hittingMethod": "Tee",
    "equipment": "Surf Board",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up the surf board and hit. Try not to hit the surf board.",
    "coachingCues": "Stay level through the zone. Keep your hands up.",
    "success": "Clean hits without hitting the surf board.",
    "bestUsedFor": "Down-up swing; dropping hands; pop-ups; contact under the ball",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Hitting Bag",
    "category": "Power",
    "primaryPurpose": "Increase intent, bat speed, and force through contact",
    "secondaryFocus": "Power",
    "hittingMethod": "Other",
    "equipment": "Hitting Dummy",
    "spaceSetup": "Open Space",
    "howItWorks": "Hit the dummy as hard as you can. 10x as hard as you can. 10x as hard AND as fast as you can.  5x as hard as you can High, Middle, and Low.",
    "coachingCues": "Swing harder, swing faster.",
    "success": "Loud, forceful contact with consistent intent at high, middle, and low targets",
    "bestUsedFor": "Low swing intent; low bat speed; weak contact; hitter needs to learn maximum-effort swings",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "Knob to Ball",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Improve hand-path accuracy by directing the knob to the ball",
    "secondaryFocus": "Taking your hands to the ball.",
    "hittingMethod": "Other",
    "equipment": "None",
    "spaceSetup": "Open Space",
    "howItWorks": "Set up, have partner toss balls into the zone about belly/chest high. Use knob of bat to pop the balls down.",
    "coachingCues": "Short motions, clean, and hit the knob to the ball hard.",
    "success": "Clean hits, bringing hands and bat back to reset.",
    "bestUsedFor": "Long hand path; poor hand accuracy; difficulty taking the hands directly to the ball",
    "mediaLink": "",
    "notes": ""
  },
  {
    "name": "One Hand Bat ",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Front hand not pulling away, Back hand pushing through.",
    "secondaryFocus": "Front hand not pulling away, Back hand pushing through.",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up tee, get down on back knee. Use front hand on short bad and practice hitting to extension with front hand only. Switch to backhand and hit ball off tee, keep front shoulder in the zone. Don't pull off.",
    "coachingCues": "Stay through the zone, keep your shoulder in the zone, don't pull off and away",
    "success": "Clean hits with your shoulders in the zone.",
    "bestUsedFor": "Shoulder and hand control hitting through the zone.",
    "mediaLink": "",
    "notes": ""
  }
];
