const assert=require('node:assert/strict');
const fs=require('node:fs');

const source=fs.readFileSync('./app.js','utf8');

function mustInclude(fragment,message){assert.ok(source.includes(fragment),message)}
function mustNotInclude(fragment,message){assert.equal(source.includes(fragment),false,message)}

mustInclude("candidateNotices:Object.fromEntries","Practice Resolution decisions must seal candidate fallback notices");
mustInclude("const survivingCandidateLabels=new Set([","Resolution must derive candidate evidence from the final filtered coaching choices");
mustInclude("if(!survivingCandidateLabels.has(label))delete verifiedCandidateNotices[label]","filtered Resolution choices must not leave stale candidate evidence");
mustInclude("Practice Resolution candidate evidence did not match the final verified choices.","Resolution must fail closed when final choices and candidate evidence diverge");
mustInclude("JSON.stringify(actualNotices)!==JSON.stringify(expectedNotices)","Resolution apply must reject changed fallback notices");
mustInclude("if(resolutionApplying||practiceResolutionApplyToken||practiceResolutionApplyDraftId||practiceResolutionApplyOwnedDraftId)return false","Resolution apply lock must survive rerenders");
mustInclude("HotB deferred setup-draft persistence during Practice Resolution apply.","temporary Resolution mutations must not persist as ordinary drafts");
mustInclude("HotB deferred navigation during Practice Resolution verification.","navigation must not escape an in-flight Resolution transaction");
mustInclude("HotB ignored End Draft while Practice Resolution apply is verifying.","End Draft must not destroy an in-flight Resolution transaction");
mustInclude("HotB Practice Resolution rebuild lost its draft authorization","owned rebuilds that lose authorization must roll back");
mustInclude("practiceResolutionApplyDraftId=null;practiceResolutionApplyOwnedDraftId=null;practiceResolutionApplyToken=null;practiceResolution=null;","practice workspace teardown must clear every Resolution identity");
mustInclude("HotB refused to persist a Practice Resolution draft that did not survive recovery serialization.","Resolution drafts must prove create/restore recovery");
mustInclude("JSON.stringify(savedResolution)!==JSON.stringify(practiceResolution)","resumed Resolution must exactly match its saved object");
mustInclude("Number(r.durationMinutes)!==120||Number(setup.durationMinutes)!==120","rollback snapshot must be bound to the failed 120-minute setup");
mustInclude("if(duration!==120)return false;","persisted Resolution snapshots must always describe the failed 120-minute source");
mustInclude("if(durationMinutes===132&&!practiceResolutionApplyDraftId)","Block 11 must require Resolution authorization");
mustInclude("HotB ignored a stale Practice Resolution rebuild callback","workspace teardown must make the first deferred Resolution callback harmless");
mustInclude("HotB Practice Resolution transaction changed during restart-recovery verification","Resolution ownership must be rechecked at the final commit boundary");
mustInclude("HotB Practice Resolution restart recovery changed the resolved setup identity","Resolution persistence must retain exact resolved setup identity");
mustInclude("HotB practice persistence changed the session during save","Resolution commit must reject save-time session mutation");
mustInclude("savedNames.some((name,index)=>name!==liveNames[index])","Resolution restart recovery must preserve exact attendee order");
mustInclude("HotB Practice Resolution restart recovery changed the resolved plan bytes","Resolution restart recovery must preserve the exact committed plan object");
mustInclude("actualNames.some((name,index)=>name!==expectedNames[index])","Resolution final plan must preserve verified attendee order");
mustInclude("expectedNames.some((name,index)=>scheduleKeys[index]!==name)","Resolution schedule ownership must preserve verified attendee order");
mustInclude("catcherLoadNames.length!==new Set(catcherLoadNames).size","Resolution catcher load metadata must reject duplicate identities");
mustInclude("practicePlan.pitcherRepeats.length!==new Set(practicePlan.pitcherRepeats).size","Resolution pitcher repeat metadata must reject duplicate identities");
mustInclude("practicePlan.liveHitterRepeats.length!==new Set(practicePlan.liveHitterRepeats).size","Resolution hitter repeat metadata must reject duplicate identities");
mustInclude("HotB refused a Practice Resolution rollback that changed during cloning","rollback clones must preserve the sealed failed-practice snapshot");
mustInclude("const releaseFailedRollback=message=>","rollback corruption must have one fail-closed transaction release path");
mustInclude("HotB could not clone the Practice Resolution rollback snapshot","rollback clone exceptions must release Resolution ownership safely");
mustInclude("if(Number(practiceSetupState.durationMinutes)!==120)practiceSetupState.durationMinutes=120;","failed rollback recovery must not leave emergency Block 11 duration live");
mustInclude("HotB Practice Resolution rollback failed post-save verification","rollback must remain valid after its recovery save");
mustInclude("if(!saved||saved.stage!=='setup'||saved.plan)return false;","Resolution apply must require the exact restart-safe setup draft before mutation");
mustInclude("selected.some((name,index)=>name!==names[index])","Resolution rollback setup must preserve exact verified attendee order");
mustInclude("!saved.resolution||JSON.stringify(saved.resolution)!==JSON.stringify(r)","Resolution rollback must be byte-identical to its persisted decision object");
mustInclude("JSON.stringify(saved.setupState)!==JSON.stringify(setup)","Resolution rollback must be byte-identical to its persisted failed setup");
mustInclude("HotB ignored Return to Practice Setup while Practice Resolution apply is verifying.","Return to Setup must not race an in-flight Resolution apply");
mustInclude("HotB refused Return to Practice Setup because the verified failed practice could not be reconstructed.","Return to Setup must reconstruct the exact verified failed practice before discarding its seal");
mustInclude("HotB could not persist Return to Practice Setup after Practice Resolution.","Return to Setup must prove its ordinary recovery draft was persisted");
mustInclude("originalReturnBytes=JSON.stringify({setupState:practiceSetupState,resolution:practiceResolution,activePracticeSession:db.activePracticeSession})","Return to Setup must seal the complete pre-exit Resolution recovery state");
mustInclude("const verifiedResolution=practiceResolutionSnapshotIsCurrentAndValid()?practiceResolution:null;","Return to Setup reconstruction must be driven only by a currently valid Resolution");
mustInclude("HotB refused Return to Practice Setup because a verified player is no longer in the attendance roster.","Return to Setup must fail closed when verified roster identity cannot be reconstructed");
mustInclude("HotB rolled back Return to Practice Setup because recovery changed the ordinary setup.","Return to Setup must restore the sealed Resolution if ordinary recovery serialization drifts");

const selectorBug="attendees=$('[data-practice-player]:checked').map";
assert.equal(source.includes(selectorBug),false,'Build Practice attendee collection must use querySelectorAll helper, never the single-element helper');
mustInclude("attendees=Array.from(document.querySelectorAll('[data-practice-player]:checked')).map","Build Practice must collect the full checked attendee set");
mustInclude("if(resolutionApplyBuild)return;\n  if(practicePlan.buildNotices?.length)","automatic Resolution rebuild must not render an uncommitted builder or notice");
mustInclude("verifiedCandidateNotices[label]=candidateNotices;\n     return true;","candidate notice evidence must publish only after the candidate passes every proof");
mustInclude("actualNames.some((name,index)=>name!==expectedNames[index])","Resolution candidate verification must preserve exact attendee order before a choice is advertised");
mustInclude("scheduleKeys.some((name,index)=>name!==planNames[index])","Resolution candidate schedule ownership must preserve exact attendee order");
mustInclude("HotB Practice Resolution build failed","Resolution candidate verification must fail closed when candidate generation throws");
mustInclude("HotB refused to publish an internally inconsistent Practice Resolution.","new Resolution decisions must pass the full live snapshot validator before display");
mustInclude("HotB could not persist the verified Practice Resolution draft.","a verified Resolution must persist successfully before its modal is shown");
mustInclude("const canonicalStringList=values=>values.length===new Set(values).size","Resolution persisted string collections must be unique and canonical");
mustInclude("candidateNoticeEntries.some(([,values])=>!canonicalStringList(values))","candidate fallback notices must remain canonical after restore");
mustInclude("candidateNoticeEntries.some(([label],index)=>index>0&&candidateNoticeEntries[index-1][0].localeCompare(label)>0)","candidate notice labels must retain canonical order");
mustInclude("HotB refused a Practice Resolution that changed during startup recovery.","startup recovery must preserve the sealed Resolution object byte-for-byte");
mustInclude("HotB ignored Practice Hub Back while Practice Resolution apply is verifying.","Practice Hub Back must not escape an in-flight Resolution transaction");
mustInclude("HotB refused Practice Hub Back because the Practice Resolution draft could not be persisted.","Practice Hub Back must not leave setup when Resolution recovery persistence fails");

const noticeCommit=source.indexOf("modal=practicePlan?.buildNotices?.length?'practiceBuildNotice':null;");
const tokenClear=source.lastIndexOf("practiceResolutionApplyToken=null;",noticeCommit);
assert.ok(tokenClear>=0&&tokenClear<noticeCommit,'Resolution build notice may appear only after the transaction token is cleared');

mustInclude("selectedNames.some((name,index)=>name!==expectedNames[index])","live Resolution validity must preserve exact verified attendee order");
mustInclude("if(duration!==120)return false;","Resolution snapshot validator must reject emergency Block 11 as source state");
mustInclude("if(!r.errors.length)return false;","Resolution snapshots must retain the original failed-build evidence");

mustInclude("const choiceAuthorized=role==='pitcher'","Resolution expected-state construction must authorize against the sealed final choice arrays");
mustInclude("Object.prototype.hasOwnProperty.call(practiceResolution.candidateNotices,'Block 11')","Block 11 apply authorization must retain its sealed candidate evidence");
mustInclude("if(!label||!Object.prototype.hasOwnProperty.call(practiceResolution.candidateNotices,label))return false;","role apply authorization must require its exact sealed candidate evidence");

mustInclude("practiceResolution=null;modal=null;","failed Resolution rollback must not leave an untrusted Resolution modal live");
mustInclude("if(Number(practiceSetupState.durationMinutes)!==120)practiceSetupState.durationMinutes=120;","failed Resolution rollback must remove transient Block 11 duration");
mustInclude("attempting sealed JSON recovery","Resolution rollback must recover from structuredClone failure using its sealed snapshot");
mustInclude("const sealed=JSON.parse(state.rollbackSignature);","Resolution rollback clone fallback must come from the already-verified rollback signature");
mustInclude("HotB could not recover the sealed Practice Resolution rollback snapshot","Resolution rollback must fail closed if sealed recovery also fails");

mustInclude("const orderedPlayers=(players||[]).map","Practice Resolution source signature must preserve verified attendee order");
mustNotInclude("})).sort((a,b)=>a.name.localeCompare(b.name));","Practice Resolution source signature must not sort away attendee-order changes");

mustInclude("const candidatePrototype=Object.getPrototypeOf(r.candidateNotices);","Resolution candidate evidence must be a plain persisted data object");
mustInclude("if(candidateNoticeEntries.length!==allowedCandidateLabels.size)return false;","Resolution candidate evidence cardinality must exactly match final choices");
mustInclude("const hasVerifiedChoice=!!(r.pitchers.length||r.catchers.length||r.canExtend||r.combinedPitchers.length||r.combinedCatchers.length);","Resolution modal actionability must come from verified choice data rather than rendered HTML");

mustInclude("const sourceBefore=JSON.stringify({practicePlayers,players});","Resolution candidate verification must seal its source player state before scheduler execution");
mustInclude("const buildPlayers=structuredClone(players);","Resolution candidate verification must give the scheduler an isolated player copy");
mustInclude("mutated sealed candidate source data during verification","Resolution candidate verification must reject scheduler mutation of its source state");
mustInclude("mutated sealed candidate source data during safety audit","Resolution candidate safety audit must remain observational");
mustInclude("changed sealed candidate source data before publication","Resolution candidate evidence must not publish after source-state mutation");

mustInclude("match(/^(\\d{1,2}):(\\d{2})$/)","Resolution clock verification must parse numeric HH:MM values");
mustNotInclude("match(/^(\\\\d{1,2}):(\\\\d{2})$/)","Resolution clock verification must not look for literal backslash-d text");
mustInclude("match(/^(\\d{2}):(\\d{2})$/)","Persisted Resolution clock validation must parse numeric HH:MM values");
mustNotInclude("match(/^(\\\\d{2}):(\\\\d{2})$/)","Persisted Resolution clock validation must not look for literal backslash-d text");


mustInclude("try{serializedDraft=JSON.stringify(draft)}catch(error){console.error('HotB refused to persist Practice Resolution because its setup draft could not be sealed.',error);return false}","Resolution draft must seal exact bytes before save and contain serialization failure");
mustInclude("HotB Practice Resolution setup draft changed during save.","Resolution draft must fail closed if save mutates recovery bytes");
mustInclude("HotB Practice Resolution setup draft failed post-save recovery verification.","Resolution draft must be restorable after the actual save");
mustInclude("const previousActivePracticeSession=db.activePracticeSession;","Resolution setup-draft persistence must retain the previous recovery authority until commit verification finishes");
mustInclude("const restorePreviousDraftAfterFailure=(message,error=null)=>","every post-save Resolution draft failure must use one rollback path");
mustInclude("db.activePracticeSession=previousActivePracticeSession;","failed Resolution setup-draft persistence must restore the previous recovery session");
mustInclude("could not restore the previous practice recovery session after setup-draft persistence failure.","Resolution draft rollback persistence failure must be contained");
mustInclude("rollback capture clone failed; attempting JSON capture","Resolution apply must retain rollback capture when structuredClone fails");
mustInclude("const captured=JSON.stringify({setupState:practiceSetupState,resolution:practiceResolution,activePracticeSession:db.activePracticeSession});","Resolution rollback fallback must seal all three transaction sources together");
mustInclude("if(JSON.stringify(state)!==captured)return null;","Resolution rollback JSON fallback must round-trip byte exactly before use");
mustInclude("if(resolutionStart===null||resolutionEnd===null)return false;","Resolution snapshot must reject an invalid derived practice clock boundary");
mustInclude("const restoredSaved=window.HotBPracticeSession?.restore?.(saved);","Resolution rollback authority must prove the saved draft through the startup restore path");
mustInclude("JSON.stringify(restoredSaved)!==JSON.stringify(saved)","Resolution rollback authority must reject restore migration or drift before apply");
mustInclude("HotB Practice Resolution live plan changed after restart-recovery verification","Resolution commit must prove the live plan still matches the exact persisted recovery plan");
mustInclude("JSON.stringify(committedSession.plan)!==JSON.stringify(practicePlan)","Resolution commit must compare live and persisted plan bytes before releasing ownership");
mustInclude("const sourceAvailability=practiceAvailability(startTime,120,player.arrivalTime,verifiedDeparture);","Block 11 must verify each source player's normal-practice availability before extension");
mustInclude("Number(player.availableFromBlock)!==Number(sourceAvailability.availableFromBlock)","Block 11 must fail closed when source availability metadata is inconsistent");
mustInclude("practiceTimeMinutes(startTime)===null","Block 11 extension must reject an invalid source clock before deriving boundaries");
mustInclude("generatedResolutionBytes=JSON.stringify(practiceResolution)","generated Resolution must be byte-sealed before publication");
mustInclude("HotB refused a Practice Resolution that changed before persistence.","generated Resolution must remain byte-identical through pre-persistence validation");
mustInclude("HotB refused a Practice Resolution that changed during publication.","published Resolution must remain byte-identical in live and saved recovery state");
mustInclude("JSON.stringify(db.activePracticeSession?.resolution)!==generatedResolutionBytes","published Resolution must verify exact persisted decision bytes before modal display");
mustInclude("HotB Practice Resolution accommodation clone failed","Resolution role mutation must fail closed if its source accommodation cannot be cloned");
mustInclude("const sourceModel=practicePlayerModel(target.roster[target.index],accommodation,practiceResolution.startTime,practiceResolution.durationMinutes);","Resolution role mutation must reconstruct its exact verified source player before changing a role");
mustInclude("sourceFields.some(field=>sourceModel[field]!==verifiedPlayer[field])","Resolution role mutation must reject stale or malformed source accommodations");
mustInclude("originalReturnBytes=JSON.stringify({setupState:practiceSetupState,resolution:practiceResolution,activePracticeSession:db.activePracticeSession})","Return to Setup must seal its entire pre-exit Resolution transaction");
mustInclude("return-state-post-save-drift","Return to Setup rollback must verify the sealed transaction after save");
mustInclude("HotB could not restore the sealed Practice Resolution Return-to-Setup state.","Return to Setup rollback must fail closed when exact recovery is impossible");
mustInclude("HotB could not clear failed Return-to-Setup recovery authority.","failed Return-to-Setup rollback must clear unsafe restart authority fail-closed");
mustNotInclude("restoreReturnState();save();render();return","Return to Setup must not perform an unverified second save after rollback");
mustInclude("const restoredRollbackSession=window.HotBPracticeSession?.restore?.(db.activePracticeSession);","Resolution rollback must prove the restored failed draft through the actual startup restore path after save");
mustInclude("JSON.stringify(restoredRollbackSession)!==JSON.stringify(restoredSession)","Resolution rollback must reject post-save restart migration or drift");
mustInclude("if(db.activePracticeSession?.resolution||db.activePracticeSession?.plan){","failed exact Resolution rollback must detect unsafe restart authority");
mustInclude("try{save()}catch(error){console.error('HotB could not clear invalid Practice Resolution rollback recovery.',error)}","failed exact Resolution rollback cleanup must contain storage failure");
mustInclude("const savedDraftBytes=JSON.stringify(db.activePracticeSession);","Resolution resume must seal the exact saved setup-stage transaction before restore");
mustInclude("restored.resolution&&JSON.stringify(restored)!==savedDraftBytes","Resolution resume must reject restore migration or defaults for unresolved decisions");
mustInclude("HotB refused Practice Resolution resume because live rollback state could not be cloned.","Resolution resume must fail closed if pre-resume live state cannot be captured");
mustInclude("HotB refused Practice Resolution resume because the restored decision could not be cloned.","Resolution resume must fail closed if the restored decision cannot be isolated");
mustInclude("verified decision could not be cloned","Resolution draft persistence must fail closed if the verified decision cannot be isolated");
mustInclude("recovery draft could not be created","Resolution draft persistence must fail closed if createDraft throws");
mustInclude("Practice Resolution recovery draft restore failed.","Resolution draft preflight restore must fail closed on restore exceptions");
mustInclude("Practice Resolution saved draft restore failed.","Resolution post-save restore must fail closed on restore exceptions");
mustInclude("JSON.stringify(persisted)!==serializedDraft","Resolution post-save restore must preserve the complete setup-stage transaction byte-for-byte");
mustInclude("practiceTimeMinutes(value){const match=","practice time parser must validate clock shape instead of coercing malformed values");
mustInclude("duration<=0?'':practiceTimeValue(start+duration)","practice end derivation must fail closed for invalid clocks or durations");
mustInclude("availableFromBlock:-1,availableUntilBlock:-1","practice availability must expose invalid time data as impossible availability");
mustInclude("if(minutes===null)return '—';","invalid practice clocks must not render as a plausible time label");
mustInclude("throw new Error('invalid-practice-start-time')","practice publication must reject an invalid start clock instead of deriving block times");
mustNotInclude("String(availability.arrivalTime||'')","rollback validation must not read arrival/departure fields that practiceAvailability does not return");
mustInclude("const rebuiltPlayer=practicePlayerModel(sourceRoster[0],accommodation,r.startTime,120);","rollback validation must reconstruct the source player through the production player model");
mustInclude("sourceFields.some(field=>rebuiltPlayer[field]!==player[field])","rollback validation must compare the complete reconstructed source player to verified Resolution state");
mustInclude("saved recovery record could not be restored.","rollback validation must fail closed if production session restore throws");
mustInclude("could not save the restored Practice Resolution rollback state","rollback recovery must fail closed if persistence throws");
mustInclude("rollback post-save restore failed.","rollback post-save restart proof must fail closed if restore throws");
mustInclude("Practice Resolution committed session restore failed","resolved commit must fail closed if restart restore throws");
mustInclude("JSON.stringify(committed)!==JSON.stringify(db.activePracticeSession)","resolved commit must preserve the complete persisted session through restart restore");
mustInclude("committed session changed during restart restore","resolved commit must reject restart migration or default drift");
mustInclude("verified setup could not be cloned.","Return-to-Setup must fail closed if verified setup isolation fails");
mustInclude("verified accommodation could not be cloned.","Return-to-Setup must fail closed if verified accommodation isolation fails");
mustInclude("stale Block 11 state could not be cloned.","Return-to-Setup must fail closed while normalizing stale emergency duration");
mustInclude("Return to Practice Setup restart restore failed.","Return-to-Setup must fail closed if restart recovery restore throws");
mustInclude("JSON.stringify(restoredExit)!==JSON.stringify(db.activePracticeSession)","Return-to-Setup must preserve the complete persisted ordinary setup session through restore");
mustInclude("could not create the practice recovery session.","resolved session persistence must fail closed if session creation throws");
mustInclude("could not seal the practice recovery session.","resolved session persistence must fail closed if session serialization throws");
mustInclude("could not save the practice recovery session.","resolved session persistence must fail closed if storage save throws");
mustInclude("could not restore the exact practice session it just persisted","resolved session persistence must require exact complete restart recovery bytes");
mustInclude("returned schedule data that could not be sealed.","candidate safety verification must reject an unserializable schedule");
mustInclude("const finishSafety=result=>","candidate safety verification must seal the schedule around the scheduler audit");
mustInclude("changed during its safety audit.","candidate safety verification must reject validator mutation of the schedule");
mustInclude("source data could not be sealed before verification.","candidate verification must fail closed if its source snapshot cannot be serialized");
mustInclude("notice evidence could not be sealed.","candidate publication must fail closed if fallback notice evidence cannot be serialized");
mustInclude("delete verifiedCandidateNotices[label]","candidate publication must remove evidence if publication verification fails");
mustInclude("changed while publishing verified candidate evidence.","candidate publication must prove evidence and source remain unchanged");
mustInclude("candidate evidence could not be sealed after final filtering.","final candidate evidence set must be serializable before Resolution publication");
mustInclude("could not verify the published Practice Resolution recovery session.","Resolution modal publication must fail closed if production recovery restore throws");
mustInclude("JSON.stringify(publishedRestored)!==publishedSessionBytes","Resolution modal publication must require exact complete persisted-session restart recovery");
mustInclude("stale at modal publication.","Resolution modal publication must revalidate the live decision snapshot after persistence");
mustInclude("Array.isArray(practiceResolution.candidateNotices['Block 11'])","Block 11 apply authorization must require verified array evidence");
mustInclude("!Array.isArray(practiceResolution.candidateNotices[label])","role apply authorization must require verified array evidence");
mustInclude("locked snapshot could not be sealed.","apply must seal the rollback Resolution before expected-state derivation");
mustInclude("expected-state derivation changed the locked snapshot.","expected-state derivation must be observational");
mustInclude("mutation changed the locked snapshot.","apply mutation must not alter the immutable rollback Resolution authority");
mustInclude("could not reconstruct the ordinary setup after rollback failure.","terminal rollback failure must prefer the sealed original 120-minute setup");
mustInclude("db.activePracticeSession=null;","terminal rollback failure must clear restart authority rather than leave a partial Resolution session");
mustInclude("could not clear failed Practice Resolution recovery authority.","terminal rollback cleanup storage failure must be contained");
mustInclude("could not clear invalid Practice Resolution rollback recovery.","post-save rollback verification cleanup storage failure must be contained");
mustInclude("final committed plan render failed","Resolution must retain transaction ownership if the committed builder cannot render");
mustInclude("transaction changed during final committed render","Resolution must recheck ownership after final committed render");
const finalRenderIndex=source.indexOf("try{render();window.scrollTo(0,0)}");
const finalTokenReleaseIndex=source.indexOf("practiceResolutionApplyToken=null;",finalRenderIndex);
assert.ok(finalRenderIndex>=0&&finalTokenReleaseIndex>finalRenderIndex,"Resolution must not consume its apply token before the committed builder renders");
mustInclude("Practice Resolution verification callback failed","the complete deferred commit verifier must have an ownership-aware exception boundary");
const verificationCallbackIndex=source.indexOf("if(!transactionOwnsToken()){console.warn('HotB ignored a stale Practice Resolution verification callback')");
const verificationTryIndex=source.lastIndexOf("try{",verificationCallbackIndex);
const verificationCatchIndex=source.indexOf("Practice Resolution verification callback failed",verificationCallbackIndex);
assert.ok(verificationCallbackIndex>=0&&verificationTryIndex>=0&&verificationCatchIndex>verificationCallbackIndex,"deferred Resolution verification must be enclosed by its own try/catch");
mustInclude("invalid-cleaned-resolution-draft","stale Resolution display cleanup must verify the replacement ordinary setup draft");
mustInclude("cleaned-resolution-draft-save-drift","stale Resolution display cleanup must verify persistence did not rewrite the replacement draft");
mustInclude("could not persist a verified clean setup after rejecting stale Practice Resolution.","stale Resolution display cleanup must contain recovery creation/save failures");
mustInclude("could not clear stale Practice Resolution recovery authority.","failed stale Resolution cleanup must clear restart authority fail-closed");
mustInclude("saved setup recovery could not be restored.","Practice Resolution resume must contain saved-draft serialization/restore failures");
mustInclude("could not persist the clean setup after rejecting a stale resumed Practice Resolution.","stale resumed Resolution cleanup must not silently continue when persistence fails");
mustInclude("resumed decision could not be sealed.","resumed Resolution byte comparison must fail closed if serialization fails");
mustInclude("could not restore the saved practice session during startup.","startup recovery must contain production session restore failures");
mustInclude("could not be isolated during startup recovery.","startup Resolution recovery must contain clone failures");
mustInclude("could not be sealed during startup recovery.","startup Resolution recovery must contain serialization failures");
mustInclude("recovery decision could not be sealed.","Resolution setup-draft persistence must contain decision serialization failures");
mustInclude("setup draft could not be sealed.","Resolution setup-draft persistence must contain draft serialization failures");
mustInclude("setup draft save failed.","Resolution setup-draft persistence must contain storage save failures");
mustInclude("saved setup draft could not be sealed.","Resolution setup-draft persistence must contain post-save serialization failures");
mustInclude("could not clear the saved practice session.","practice workspace teardown must contain recovery-session clear save failures");
mustInclude("saved practice session remained after clear.","practice workspace teardown must verify recovery authority is actually cleared");
mustInclude("refused to close the practice workspace because recovery state could not be cleared.","Practice Resolution workspace teardown must fail closed before discarding live state");
console.log('practice-resolution static contract tests passed');
