(() => {
  const BUILD_VERSION = '2026.10.09.571';
  window.HOTB_BUILD_VERSION = BUILD_VERSION;
  const params=new URLSearchParams(window.location.search);
  if (params.has('portal')) return;
  if(params.get('source')==='pwa'&&!params.has('homeStart')){try{const key='hotbRebuildDbV1',db=JSON.parse(localStorage.getItem(key)||'{}');db.route='home';localStorage.setItem(key,JSON.stringify(db));const u=new URL(location.href);u.searchParams.set('homeStart','1');location.replace(u.href);return}catch(_){}}
  const runtimeSafety=document.createElement('script');runtimeSafety.src='practice-bypass.js?v=20261007-undo10';runtimeSafety.async=false;document.head.appendChild(runtimeSafety);
  const nightFixes=document.createElement('link');nightFixes.rel='stylesheet';nightFixes.href='hotb-night-fixes.css?v=20261007-1';document.head.appendChild(nightFixes);
  const observationStyles=document.createElement('link');observationStyles.rel='stylesheet';observationStyles.href='observation-publish-v2.css?v=20261008-full-picker-1';document.head.appendChild(observationStyles);
  const observationPublish=document.createElement('script');observationPublish.src='observation-publish-v2.js?v=20261008-gated-actions-1';observationPublish.async=false;document.head.appendChild(observationPublish);
  const practiceFocus=document.createElement('script');practiceFocus.src='practice-focus-integration.js?v=20261009-focus-practice-16';practiceFocus.async=false;document.head.appendChild(practiceFocus);
  const focusPageCleanup=document.createElement('script');focusPageCleanup.src='focus-page-cleanup-v1.js?v=20261009-566';focusPageCleanup.async=false;document.head.appendChild(focusPageCleanup);
  const focusCancelGuard=document.createElement('script');focusCancelGuard.src='focus-modal-cancel-v1.js?v=20261009-570';focusCancelGuard.async=false;document.head.appendChild(focusCancelGuard);
  const focusFollowthrough=document.createElement('script');focusFollowthrough.src='player-focus-followthrough-v1.js?v=20261009-571';focusFollowthrough.async=false;document.head.appendChild(focusFollowthrough);
  if (!('serviceWorker' in navigator) || !window.isSecureContext) return;
  let updateShown=false,updateAccepted=sessionStorage.getItem('hotbUpdateAccepted')===BUILD_VERSION;const hadControllerAtLoad=Boolean(navigator.serviceWorker.controller);
  function showUpdate(version='new'){if(updateShown||updateAccepted)return;updateShown=true;const notice=document.createElement('aside');notice.className='pwa-update-notice';notice.setAttribute('role','status');notice.innerHTML='<span>New HotB version available</span><button type="button">UPDATE NOW</button>';notice.querySelector('button').addEventListener('click',()=>{const button=notice.querySelector('button');button.disabled=true;button.textContent='UPDATING…';updateAccepted=true;sessionStorage.setItem('hotbUpdateAccepted',BUILD_VERSION);try{navigator.serviceWorker.getRegistration('./').then(registration=>{try{registration?.waiting?.postMessage({type:'SKIP_WAITING'})}catch(_){}try{registration?.update()}catch(_){}}).catch(()=>{})}catch(_){}const url=new URL('./',window.location.href);url.searchParams.set('source','pwa');url.searchParams.set('launch','571');url.searchParams.delete('homeStart');url.searchParams.set('hotb-update',version);url.searchParams.set('reload',Date.now().toString());window.location.replace(url.href)});document.body.appendChild(notice)}
  async function checkForUpdate(registration){if(navigator.onLine){try{await registration.update()}catch(_){}}if(registration.waiting)showUpdate('waiting-worker')}
  window.addEventListener('load',async()=>{try{const registration=await navigator.serviceWorker.register('./service-worker-v571.js',{scope:'./',updateViaCache:'none'});await checkForUpdate(registration);registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)showUpdate('installed-worker')})});window.addEventListener('pageshow',()=>checkForUpdate(registration));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')checkForUpdate(registration)})}catch(_){}});
  navigator.serviceWorker.addEventListener('controllerchange',()=>{if(hadControllerAtLoad)showUpdate('controller-changed')});navigator.serviceWorker.addEventListener('message',event=>{if(event.data?.type==='HOTB_UPDATE_READY'&&event.data.version!==BUILD_VERSION)showUpdate(event.data.version)});
})();