(()=>{
 const DBKEY='hotbRecruitingV1',PLAYER='Brooklyn Gering';
 const clean=v=>String(v??'').trim();
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 function read(){try{return JSON.parse(localStorage.getItem(DBKEY)||'{}')||{}}catch{return{}}}
 function save(v){localStorage.setItem(DBKEY,JSON.stringify(v))}
 function value(){return clean(read().players?.[PLAYER]?.motto)}
 function close(){document.querySelector('.rw-motto-backdrop')?.remove()}
 async function publish(motto){try{if(!window.firebase?.apps?.length)return;const user=firebase.auth().currentUser;if(!user||user.isAnonymous)return;await firebase.firestore().collection('recruitingProfiles').doc('brooklyn-gering').set({motto},{merge:true})}catch(e){console.warn('Motto publish pending.',e)}}
 function open(){document.body.insertAdjacentHTML('beforeend',`<div class="rw-backdrop rw-motto-backdrop"><section class="rw-modal"><div class="rw-modal-head"><div><span>PLAYER MOTTO</span><h2>Brooklyn Gering</h2></div><button class="rw-close" id="rwMottoClose">Close</button></div><p class="rw-help">Keep it short—one sentence or brief phrase in Brooklyn's own voice.</p><label class="rw-label">Player Motto<input id="rwMottoInput" maxlength="160" value="${esc(value())}" placeholder="Enter Brooklyn's motto"></label><div class="rw-actions"><button class="rw-secondary" id="rwMottoCancel">Cancel</button><button class="rw-primary" id="rwMottoSave">Save Motto</button></div></section></div>`);document.querySelector('#rwMottoClose').onclick=close;document.querySelector('#rwMottoCancel').onclick=close;document.querySelector('#rwMottoSave').onclick=async()=>{const motto=clean(document.querySelector('#rwMottoInput').value),store=read();store.players=store.players||{};store.players[PLAYER]={...(store.players[PLAYER]||{}),motto,mottoUpdatedAt:new Date().toISOString()};save(store);await publish(motto);close();wire()}}
 function wire(){const section=document.querySelector('#rwRecruitingSection'),select=document.querySelector('#evalSelect');if(!section||select?.value!==PLAYER)return;let row=section.querySelector('.rw-motto-line');if(!row){row=document.createElement('div');row.className='rw-eval-line rw-motto-line';row.innerHTML='<span><b>Player Motto:</b> <span class="rw-motto-value"></span></span><button class="rw-evaluation-link rw-motto-edit">Edit</button>';const evalRow=section.querySelector('.rw-eval-line');if(evalRow)evalRow.before(row);else section.append(row);row.querySelector('.rw-motto-edit').onclick=open}row.querySelector('.rw-motto-value').textContent=value()||'Not set'}
 const obs=new MutationObserver(()=>requestAnimationFrame(wire));obs.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});document.addEventListener('change',e=>{if(e.target?.id==='evalSelect')setTimeout(wire,0)});wire();
})();
