const assert=require('node:assert/strict');
const workflow=require('./recruiting-workflow.js');
const brooklyn={name:'Brooklyn Gering',grad:'2029',positions:'RHP | OF',gpa:'4.0',jersey:'16',coachEvaluation:'Brooklyn competes.'};
const megan={name:'Megan Ryan',grad:'2028',positions:'RHP | UT',gpa:'4.00',jersey:'22',coachEvaluation:'Megan is versatile.'};
assert.equal(workflow.activePlayer('Brooklyn Gering'),true);
assert.equal(workflow.activePlayer('Megan Ryan'),true);
assert.equal(workflow.activePlayer('Team'),false);
assert.equal(workflow.slugFor('Megan Ryan'),'megan-ryan');
assert.match(workflow.profileUrl('Megan Ryan'),/player=megan-ryan/);
assert.equal(workflow.buildEmailSubject(brooklyn),'Brooklyn Gering | 2029 | RHP/OF | 4.0 GPA | #16');
const body=workflow.buildPlayerEmailBody(megan,'Smith');
assert.match(body,/Coach Smith,/);
assert.match(body,/Megan Ryan/);
assert.match(body,/player=megan-ryan/);
assert.match(body,/PLAYER PROFILE \/ CURRENT RESULTS/);
assert.match(body,/UPCOMING SCHEDULE/);
assert.match(body,/GAMECHANGER/);
const coaches=[{coachName:'Coach Alpha',collegeName:'Kansas College'},{coachName:'Coach Beta',collegeName:'Missouri College'}];
assert.equal(workflow.coachMatches(coaches,'alpha','coachName')[0].coachName,'Coach Alpha');
assert.equal(workflow.coachMatches(coaches,'kansas','collegeName')[0].collegeName,'Kansas College');
console.log('recruiting-workflow full-roster tests passed');
