const fs=require('fs');
const assert=require('assert');
const app=fs.readFileSync('app.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
const names=['Neveah Schlappi','Lilliana Schlappi','Taylor Woods','Perri Wagner','Pacie Dougherty','Amelia Steffen','Emmie Wible','Leslie Cundiff'];
names.forEach(name=>assert.ok(app.includes(name),'missing Team Jenkins player: '+name));
assert.ok(app.includes("teamName:'Team Jenkins'"),'Jenkins records are explicitly tagged');
assert.ok(app.includes("function practiceAttendanceRoster(){return [...db.roster,...practiceGuestPlayers()]}"),'scheduler attendance roster includes Team Jenkins');
assert.ok(app.includes("const positions=positionTokens(player);"),'scheduler derives pitcher/catcher roles from Jenkins positions');
assert.ok(app.includes("canPitch:model.isPitcher&&accommodation.canPitch!==false"),'Jenkins pitchers participate in normal pitching availability');
assert.ok(app.includes("canCatch:model.isCatcher&&accommodation.canCatch!==false"),'Jenkins catchers participate in normal catching availability');
assert.ok(app.includes('function competitionRoster(){return db.roster.filter(player=>!player.isTeamJenkins)}'),'all competition/game surfaces exclude Team Jenkins');
assert.ok(app.includes("permanentPlayers=db.roster.filter(player=>!player.isGuest&&!player.isTeamJenkins)"),'practice history attendance excludes Team Jenkins');
assert.ok(app.includes('TEAM JENKINS'),'practice setup has Team Jenkins heading');
assert.ok(app.includes('team-jenkins-practice-section'),'practice setup has isolated Jenkins section');
assert.ok(css.includes('.practice-attendance-row.team-jenkins-player'),'Jenkins rows have distinct gray styling');
assert.ok(app.includes("portalType:'jenkinsPlayer'"),'Jenkins receives a dedicated reusable portal type');
assert.ok(app.includes("accessStatus:'waiting'"),'Jenkins portal returns to waiting after practice');
assert.ok(app.includes("expired:false"),'Jenkins portal remains valid after practice');
assert.ok(app.includes("portalData.portalType==='jenkinsPlayer')return !portalData.activePractice||activePracticeEnded?guestPortalWaitingView():portalPracticeView()"),'Jenkins portal can render only waiting or current practice');
assert.ok(app.includes("portalData?.portalType!=='jenkinsPlayer'&&drillAssignments.length"),'Jenkins portal does not expose assigned-drill library section');
assert.ok(app.includes("jenkins=portalData?.portalType==='jenkinsPlayer'"),'Jenkins drill links are disabled');
assert.ok(app.includes("No practice is active right now. Use this same link the next time you practice with us."),'reusable no-practice state exists');
assert.ok(app.includes("Team Jenkins · current Hitting Practice only"),'share UI states the access boundary');
console.log('team-jenkins-practice-only tests passed');

assert.ok(app.includes("async function setupJenkinsPortals()"),'portal manager has Team Jenkins setup action');
assert.ok(app.includes("$('#setupJenkinsPortals')?.addEventListener('click',setupJenkinsPortals)"),'Team Jenkins setup button is bound');
assert.ok((app.match(/\$\$\('\[data-share-practice-jenkins\]'\)/g)||[]).length>=2,'Team Jenkins share buttons are bound in manager and practice views');
